### ISSUE TITLE
Unable to login 

### ISSUE THREAD

**Issue by Pratipkhandelwal** [haxxorsid/food-ordering-system#4]
Trying to login with the user details given in the user table cannot log in , it just stays at the same page .
How to login ?

**Comment by haxxorsid** [comment]
I don't remember what PHP version I used to run this. But if you're using PHP7 try out PHP5. 6 or vice versa. MYSQL commands compatibility is different for both. Also make sure your MYSQL username and password is set correctly.

**Comment by Pratipkhandelwal** [comment]
I'm using xampp and php version is 5.6 .The username i took is default given like user1 and pass1 to login in the user table. Trying to work it out but still error persists somewhere .

**Comment by Pratipkhandelwal** [comment]
Thanks it's done now .
