### ISSUE TITLE
Not login after use username and password

### ISSUE THREAD

**Issue by r3j3c73d** [haxxorsid/food-ordering-system#6]
Hi, I am trying your project, it's beautiful, I want to login to it with this user and password:
root/toor
as in database, but when i hit login button it's just refreshed and nothing happened, what's wrong?

**Comment by haxxorsid** [comment]
Maybe Mysqli is not enabled in your PHP. Enable it if not. 
If everything is fine, check if the Database name is 'food' and SQL script was successfully imported in Mysql Database.

**Comment by r3j3c73d** [comment]
I added mysqli in php7 config file, then reload it,
also in ubuntu 16.04 and after that we need to remove root user from mysql users then create it again because it need sudo permission 
also we need to modify connect.php file in include folder if we create user and password for mysql user.
thank you for this project and your help

**Comment by haxxorsid** [comment]
Cool.
